### ISSUE TITLE
`info_player_start` transform conflict

### ISSUE THREAD

**Issue by VortexParadox** [ChaosInitiative/Chaos-FGD#113]
The semi-recent changes to add a custom player_start model have caused the transforms to the entity to be performed twice

Removing `studio()` fixes this, but I'm unaware of the repercussions, if any.

**Comment by AWildErin** [comment]
`studio()` was removed on `info_player_start` in 26b49b12aba97e9a81b3f48a6b93aafe89efefb6, not sure if the transform issue is still persistent though.

**Comment by Luke18033** [comment]
It should have `studio()` only, since that makes it use the fixed-size bounding box which matches the player's instead of resizing it dynamically based on the model's orientation. Let's please just remove the model selector, the only reason it was added was for the stupid catboy model, just override the original if you want to use that.

**Comment by hexaflexahexagon** [comment]
> It should have `studio()` only, since that makes it use the fixed-size bounding box which matches the player's instead of resizing it dynamically based on the model's orientation. Let's please just remove the model selector, the only reason it was added was for the stupid catboy model, just override the original if you want to use that.

Agreed, it has only caused issues for something that can be done with a prop_static in 10 seconds.

**Comment by AWildErin** [comment]
Yeah, I agree with that, it was a stupid addition imho and, as Hex said, can be solved with a prop static

**Comment by TeamSpen210** [comment]
The double-rotation issue occurs if there's multiple `studio()`/`studioprop()` helpers present, since each individually applies the rotation.
