### ISSUE TITLE
Update from latest upstream

### ISSUE THREAD

**Issue by Gocnak** [ChaosInitiative/Chaos-FGD#19]
Not precisely everything but the base FGD fixes along with the texture touchups would be great.

**Comment by braem** [comment]
Going to skip the material exclusion commits as it looks like it was mainly added to work with TF2 hammer: https://github.com/TeamSpen210/HammerAddons/issues/108
Unless there is some merit in adding it for Chaos? I'm not super familiar with it tbh.

**Comment by TeamSpen210** [comment]
You might want to merge the `unify_fgd.py` parts, since then you can define those and it'll be exported properly. It's mostly useful to hide mats you don't need, say the `models/` or `vgui/` folder.

**Comment by braem** [comment]
> 
> 
> You might want to merge the `unify_fgd.py` parts, since then you can define those and it'll be exported properly. It's mostly useful to hide mats you don't need, say the `models/` or `vgui/` folder.

Oh that's what that's for! doh
Definitely would be useful to have yeah. Really odd TF2's hammer crashes without that though haha
