### ISSUE TITLE
Per-game gameconfig defaults

### ISSUE THREAD

**Issue by braem** [ChaosInitiative/Chaos-FGD#37]
Currently, P2CE's default gameconfig includes momentum & vice versa. Makes little sense as hammer wont even work in those situations (wont find FGD, etc).

**Comment by Gocnak** [comment]
This will most likely need to expand to include the CmdSeqDefault as Momentum has ZonMaker as a custom step that P2CE doesn't need.

**Comment by braem** [comment]
We should be able to use the `property_parser` module in srctools to read these https://github.com/TeamSpen210/srctools/blob/master/srctools/property_parser.py

**Comment by Gocnak** [comment]
I was thinking just template files and then the build script replaces the template with the specific game stuff.

**Comment by braem** [comment]
> 
> 
> I was thinking just template files and then the build script replaces the template with the specific game stuff.

Yeah that'd be easier. Would making building all nonsensical though. Or maybe have it output to respective game folders in that case, like `build/momentum/` & `build/p2ce`.
