### ISSUE TITLE
Change "Name" property in Entity filter_activator_name to "targetname"

### ISSUE THREAD

**Issue by Gocnak** [ChaosInitiative/Chaos-FGD#41]
As requested from pretzl:

For ease of understanding, the "name" property in the entity filter_activator_name should be changed to "targetname" since this is really what it is. Triggers use this name to call to the filter entity with the convention "targetname <name>", but as-is can be confusing at times.

Make sure to do this in game code as well!

**Comment by braem** [comment]
I'm a little confused by this request - triggers have a "Filter name" field for filters, not "targetname". Every entity has a "Name" field, so it'd be quite out of place to change it to "targetname" for 1 entity. The only place "targetname" shows up is with smartedit off, and I don't think we need to worry about legibility in that case.

Unless the request is to rename the field in the filter "Filter Name" to "Target name", which would be a simple rename in the FGD; no code change required.

**Comment by hexaflexahexagon** [comment]
i'm also not too sure what it's asking. every entity has a "name" keyvalue which is the name by which any other entity would refer to it (e.g. `OnStartTouch -> myCoolDoor -> open`), this is consistent in both this filter and everywhere else. This filter also has a second keyvalue called "Filter Name" which is what it compares against to do filtering which also shouldn't change imo. All assuming smart edit on which I think is a fair assumption. See the pictures below. 

either something has changed between now and when the feature was originally suggested or this is worded in a confusing way and i'm completely missing the point. we could reach out to ask the original submitter what they meant but just closing this instead also works for me.

![image](https://user-images.githubusercontent.com/62961532/123493946-27b36b00-d5ec-11eb-8454-a9d2b78f292a.png)
![image](https://user-images.githubusercontent.com/62961532/123493953-313cd300-d5ec-11eb-9755-b990125c99ff.png)

**Comment by Gocnak** [comment]
I'm fine with just closing this then. It can be resuggested better in the future, this was copied from the old hammer repo.
