### ISSUE TITLE
Default `game_text` location to somewhere other than the center of the screen

### ISSUE THREAD

**Issue by hexaflexahexagon** [ChaosInitiative/Chaos-FGD#85]
By default the location of a new `game_text` entity is -1, -1 which centers the text both horizontally and vertically. If a mapper forgets to change this, this places the text right over the player's crosshair which can be very frustrating. A more acceptable default would be x = -1 and y = 0.7. See below comparison. Obviously this won't affect existing maps but it should prevent more in the future from making this mistake.

![image](https://user-images.githubusercontent.com/62961532/134823754-890f857f-3fd9-4ccc-9527-5bc7a40bf59e.png)
![image](https://user-images.githubusercontent.com/62961532/134823763-46c1f75e-5b93-4db2-996c-8746998e4660.png)

**Comment by Luke18033** [comment]
Related, what's the point of `-1` to center in these keyvalues? Is that not the same as `0.5`?

**Comment by hexaflexahexagon** [comment]
No clue, im guessing just a shorthand. AFAIK 0.5 and -1 are the same yeah. Unless -1 horizontal will center-align the text while 0.5 horizontal just starts typing at the center of the screen or something silly lol
