### ISSUE TITLE
info_player_start has a doubled model helper

### ISSUE THREAD

**Issue by Luke18033** [ChaosInitiative/Chaos-FGD#89]
`info_player_start` has both `studio` and `studioprop` helpers, resulting in it having two hitbox outlines, and rotating it with the handles causes it to rotate by twice the amount. It should only have `studio` (since the hitbox is supposed to be a fixed size representing the player).

**Comment by Gocnak** [comment]
Gonna ping @Trico-Everfire as this relates to their recent change.
