### ISSUE TITLE
Make linked_portal_door StartActive "yes" by default

### ISSUE THREAD

**Issue by hexaflexahexagon** [ChaosInitiative/Chaos-FGD#97]
I don't know if p2ce likes it better this way with how maps use portals, if so consider game-locking this

Suggested by touny

**Comment by Luke18033** [comment]
It would probably be good to switch this based on game, in Portal you often have worldportals behind doors where you don't want them to open until the door itself opens.

**Comment by tmob03** [comment]
Can be closed ^^
